version: "3.10"

services:
  yourstock: #サービス名
    build:
      context: ./yourstock #Dockerfileのあるディレクトリ
      dockerfile: Dockerfile #Dockerfileのファイル名
    volumes: #バインドマウント
      - type: bind
        source: ./yourstock/src
        target: /usr/src/app/src
      - type: bind
        source: ./yourstock/public
        target: /usr/src/app/public
    command: yarn build && yarn firebase deploy
    tty: true
    ports:
      - "3000:3000"